# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './settings.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import simulator_gui as sim

class Ui_StartingSettings(object):
    def setupUi(self, StartingSettings):
        StartingSettings.setObjectName("StartingSettings")
        StartingSettings.setFixedSize(796, 371)
        self.centralwidget = QtWidgets.QWidget(StartingSettings)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.generalBox = QtWidgets.QGroupBox(self.centralwidget)
        self.generalBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generalBox.sizePolicy().hasHeightForWidth())
        self.generalBox.setSizePolicy(sizePolicy)
        self.generalBox.setMaximumSize(QtCore.QSize(900, 1000))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.generalBox.setFont(font)
        self.generalBox.setMouseTracking(False)
        self.generalBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.generalBox.setAccessibleDescription("")
        self.generalBox.setFlat(False)
        self.generalBox.setCheckable(False)
        self.generalBox.setChecked(False)
        self.generalBox.setObjectName("generalBox")
        self.label = QtWidgets.QLabel(self.generalBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.generalBox)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinShaftsAmount = QtWidgets.QSpinBox(self.generalBox)
        self.spinShaftsAmount.setGeometry(QtCore.QRect(140, 50, 101, 22))
        self.spinShaftsAmount.setMinimum(1)
        self.spinShaftsAmount.setMaximum(100)
        self.spinShaftsAmount.setProperty("value", 2)
        self.spinShaftsAmount.setObjectName("spinShaftsAmount")
        self.spinFloorsAmount = QtWidgets.QSpinBox(self.generalBox)
        self.spinFloorsAmount.setGeometry(QtCore.QRect(140, 90, 101, 22))
        self.spinFloorsAmount.setMinimum(2)
        self.spinFloorsAmount.setMaximum(100)
        self.spinFloorsAmount.setProperty("value", 6)
        self.spinFloorsAmount.setObjectName("spinFloorsAmount")
        self.gridLayout.addWidget(self.generalBox, 0, 1, 1, 1)
        self.elevatorBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elevatorBox.sizePolicy().hasHeightForWidth())
        self.elevatorBox.setSizePolicy(sizePolicy)
        self.elevatorBox.setMaximumSize(QtCore.QSize(800, 800))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.elevatorBox.setFont(font)
        self.elevatorBox.setObjectName("elevatorBox")
        self.label_4 = QtWidgets.QLabel(self.elevatorBox)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.elevatorBox)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.elevatorBox)
        self.label_7.setGeometry(QtCore.QRect(40, 120, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.elevatorBox)
        self.label_8.setGeometry(QtCore.QRect(40, 160, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.elevatorBox)
        self.label_9.setGeometry(QtCore.QRect(40, 200, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.elevatorBox)
        self.label_10.setGeometry(QtCore.QRect(40, 240, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.elevatorBox)
        self.label_11.setGeometry(QtCore.QRect(40, 280, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.spinCapacity = QtWidgets.QSpinBox(self.elevatorBox)
        self.spinCapacity.setGeometry(QtCore.QRect(130, 40, 101, 22))
        self.spinCapacity.setObjectName("spinCapacity")
        self.spinCapacity.setValue(10)
        self.spinMoving = QtWidgets.QSpinBox(self.elevatorBox)
        self.spinMoving.setGeometry(QtCore.QRect(130, 120, 101, 22))
        self.spinMoving.setMinimum(1)
        self.spinMoving.setMaximum(999999999)
        self.spinMoving.setSingleStep(1)
        self.spinMoving.setObjectName("spinMoving")
        self.spinMoveToStop = QtWidgets.QSpinBox(self.elevatorBox)
        self.spinMoveToStop.setGeometry(QtCore.QRect(130, 160, 101, 22))
        self.spinMoveToStop.setMinimum(1)
        self.spinMoveToStop.setMaximum(9999999)
        self.spinMoveToStop.setObjectName("spinMoveToStop")
        self.spinStopToMove = QtWidgets.QSpinBox(self.elevatorBox)
        self.spinStopToMove.setGeometry(QtCore.QRect(130, 200, 101, 22))
        self.spinStopToMove.setMinimum(1)
        self.spinStopToMove.setMaximum(9999999)
        self.spinStopToMove.setObjectName("spinStopToMove")
        self.spinLoading = QtWidgets.QSpinBox(self.elevatorBox)
        self.spinLoading.setGeometry(QtCore.QRect(130, 240, 101, 22))
        self.spinLoading.setMinimum(1)
        self.spinLoading.setMaximum(9999999)
        self.spinLoading.setObjectName("spinLoading")
        self.spinUnloading = QtWidgets.QSpinBox(self.elevatorBox)
        self.spinUnloading.setGeometry(QtCore.QRect(130, 280, 101, 22))
        self.spinUnloading.setMinimum(1)
        self.spinUnloading.setMaximum(9999999)
        self.spinUnloading.setObjectName("spinUnloading")
        self.gridLayout.addWidget(self.elevatorBox, 0, 0, 2, 1)
        self.passengerBox = QtWidgets.QGroupBox(self.centralwidget)
        self.passengerBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passengerBox.sizePolicy().hasHeightForWidth())
        self.passengerBox.setSizePolicy(sizePolicy)
        self.passengerBox.setMaximumSize(QtCore.QSize(900, 900))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.passengerBox.setFont(font)
        self.passengerBox.setFlat(False)
        self.passengerBox.setCheckable(False)
        self.passengerBox.setObjectName("passengerBox")
        self.label_6 = QtWidgets.QLabel(self.passengerBox)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spinPeopleAmount = QtWidgets.QSpinBox(self.passengerBox)
        self.spinPeopleAmount.setGeometry(QtCore.QRect(140, 40, 101, 22))
        self.spinPeopleAmount.setMinimum(1)
        self.spinPeopleAmount.setMaximum(9999999)
        self.spinPeopleAmount.setProperty("value", 200)
        self.spinPeopleAmount.setObjectName("spinMaxWaitingTime")
        self.label_13 = QtWidgets.QLabel(self.passengerBox)
        self.label_13.setGeometry(QtCore.QRect(20, 80, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBoxDistr = QtWidgets.QComboBox(self.passengerBox)
        self.comboBoxDistr.setGeometry(QtCore.QRect(30, 110, 201, 22))
        self.comboBoxDistr.setObjectName("comboBoxDistr")
        self.comboBoxDistr.addItem("")
        self.comboBoxDistr.addItem("")
        self.comboBoxDistr.addItem("")
        self.comboBoxDistr.addItem("")
        self.gridLayout.addWidget(self.passengerBox, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.spinSeed = QtWidgets.QSpinBox(self.groupBox)
        self.spinSeed.setGeometry(QtCore.QRect(130, 80, 111, 22))
        self.spinSeed.setMaximum(999999999)
        self.spinSeed.setSingleStep(1)
        self.spinSeed.setDisplayIntegerBase(10)
        self.spinSeed.setObjectName("spinSeed")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 80, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBoxFitness = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxFitness.setGeometry(QtCore.QRect(130, 120, 111, 22))
        self.comboBoxFitness.setObjectName("comboBoxFitness")
        self.comboBoxFitness.addItem("")
        self.comboBoxFitness.addItem("")
        self.comboBoxFitness.addItem("")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(20, 160, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 280, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.comboBoxComputationEffort = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxComputationEffort.setGeometry(QtCore.QRect(130, 280, 111, 22))
        self.comboBoxComputationEffort.setObjectName("comboBoxComputationEffort")
        self.comboBoxComputationEffort.addItem("")
        self.comboBoxComputationEffort.addItem("")
        self.comboBoxComputationEffort.addItem("")
        self.spinCrossoverProb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinCrossoverProb.setGeometry(QtCore.QRect(130, 200, 111, 22))
        self.spinCrossoverProb.setMaximum(1.0)
        self.spinCrossoverProb.setSingleStep(0.01)
        self.spinCrossoverProb.setProperty("value", 0.7)
        self.spinCrossoverProb.setObjectName("spinCrossoverProb")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(20, 200, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.spinMutationProb = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinMutationProb.setGeometry(QtCore.QRect(130, 240, 111, 22))
        self.spinMutationProb.setDecimals(3)
        self.spinMutationProb.setMaximum(1.0)
        self.spinMutationProb.setSingleStep(0.001)
        self.spinMutationProb.setProperty("value", 0.01)
        self.spinMutationProb.setObjectName("spinMutationProb")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(20, 240, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.comboBoxPopulationSize = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxPopulationSize.setGeometry(QtCore.QRect(130, 160, 111, 22))
        self.comboBoxPopulationSize.setObjectName("comboBoxPopulationSize")
        self.comboBoxPopulationSize.addItem("")
        self.comboBoxPopulationSize.addItem("")
        self.comboBoxPopulationSize.addItem("")
        self.comboBoxPopulationSize.addItem("")
        self.comboBoxPopulationSize.addItem("")
        self.spinTotalDuration = QtWidgets.QSpinBox(self.groupBox)
        self.spinTotalDuration.setGeometry(QtCore.QRect(130, 40, 111, 22))
        self.spinTotalDuration.setSuffix("")
        self.spinTotalDuration.setMaximum(999999999)
        self.spinTotalDuration.setSingleStep(1)
        self.spinTotalDuration.setProperty("value", 3600)
        self.spinTotalDuration.setDisplayIntegerBase(10)
        self.spinTotalDuration.setObjectName("spinTotalDuration")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(20, 40, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.groupBox, 0, 2, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setObjectName("buttonStart")
        self.gridLayout_2.addWidget(self.buttonStart, 1, 0, 1, 1)
        StartingSettings.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartingSettings)
        self.comboBoxPopulationSize.setCurrentIndex(2)
        self.bindEvents()
        QtCore.QMetaObject.connectSlotsByName(StartingSettings)


    def bindEvents(self):

        #Action of the "Start" button
        self.buttonStart.clicked.connect(lambda l : [setInitialParameters()])

        #temp tmp
        self.spinMoving.setValue(1)
        self.spinMoveToStop.setValue(1)
        self.spinStopToMove.setValue(1)
        self.spinLoading.setValue(1)
        self.spinUnloading.setValue(1)
        self.comboBoxComputationEffort.setCurrentIndex(2)
        self.comboBoxPopulationSize.setCurrentIndex(4)
        self.comboBoxFitness.setCurrentIndex(2)


        def setInitialParameters():
            global settingsGuiWindow
            SETTINGS = {
                "total_duration" : self.spinTotalDuration.value(),
                "shafts_amount" : self.spinShaftsAmount.value(),
                "floors_amount" : self.spinFloorsAmount.value(),
                "elevator" : {
                    "capacity" : self.spinCapacity.value(),
                    "timing" : { # in seconds
                        # movimento da un piano ad un altro
                        'moving' : self.spinMoving.value(),
                
                         # decelerazione + apertura_porte
                        'move_to_stop' : self.spinMoveToStop.value(),
                
                        # chiusura_porte + accelerazione
                        'stop_to_move' : self.spinStopToMove.value(),
                
                        # caricamento_passeggeri + selezione_piano
                        'loading' : self.spinLoading.value(),
                
                        # scaricamento passeggeri
                        'unloading' : self.spinUnloading.value()
                    }
                },
                "passenger" : {
                    "people_amount" : self.spinPeopleAmount.value(),
                    "distribution" : self.comboBoxDistr.currentIndex()
                },
                "ga" : {
                    "seed" : self.spinSeed.value(),
                    "fitness" : self.comboBoxFitness.currentIndex(),
                    "population_size" : self.comboBoxPopulationSize.currentText().lower(),
                    "crossover_prob" : self.spinCrossoverProb.value(),
                    "mutation_prob" : self.spinMutationProb.value(),
                    "computation_effort" : self.comboBoxComputationEffort.currentIndex()
                }
            }
            #print(SETTINGS)

            settingsGuiWindow = QtWidgets.QMainWindow()
            ui = sim.simulatorGui(SETTINGS)
            ui.setupGui(settingsGuiWindow)
            settingsGuiWindow.show()


    def retranslateUi(self, StartingSettings):
        _translate = QtCore.QCoreApplication.translate
        StartingSettings.setWindowTitle(_translate("StartingSettings", "Model Setup"))
        self.generalBox.setTitle(_translate("StartingSettings", "Building"))
        self.label.setText(_translate("StartingSettings", "Shafts Amount:"))
        self.label_2.setText(_translate("StartingSettings", "Floors Amount:"))
        self.elevatorBox.setTitle(_translate("StartingSettings", "Elevator"))
        self.label_4.setText(_translate("StartingSettings", "Capacity:"))
        self.label_5.setText(_translate("StartingSettings", "Timers (sec):"))
        self.label_7.setText(_translate("StartingSettings", "Moving:"))
        self.label_8.setText(_translate("StartingSettings", "Move To Stop:"))
        self.label_9.setText(_translate("StartingSettings", "Stop To Move:"))
        self.label_10.setText(_translate("StartingSettings", "Loading:"))
        self.label_11.setText(_translate("StartingSettings", "Unloading"))
        self.passengerBox.setTitle(_translate("StartingSettings", "Passenger"))
        self.label_6.setText(_translate("StartingSettings", "People amount:"))
        self.label_13.setText(_translate("StartingSettings", "Calling distribution:"))
        self.comboBoxDistr.setItemText(0, _translate("StartingSettings", "[0] Random"))
        self.comboBoxDistr.setItemText(1, _translate("StartingSettings", "[1] Morning Up-peak"))
        self.comboBoxDistr.setItemText(2, _translate("StartingSettings", "[2] Evening Up-peak"))
        self.comboBoxDistr.setItemText(3, _translate("StartingSettings", "[3] Up-peak + turn change"))
        self.groupBox.setTitle(_translate("StartingSettings", "Genetic Algorithm"))
        self.label_12.setText(_translate("StartingSettings", "Initial Seed:"))
        self.label_3.setText(_translate("StartingSettings", "Fitness function:"))
        self.comboBoxFitness.setItemText(0, _translate("StartingSettings", "Standard GA"))
        self.comboBoxFitness.setItemText(1, _translate("StartingSettings", "GA with NS"))
        self.comboBoxFitness.setItemText(2, _translate("StartingSettings", "Optimistic GA"))
        self.label_14.setText(_translate("StartingSettings", "Population size:"))
        self.label_15.setText(_translate("StartingSettings", "Computation effort:"))
        self.comboBoxComputationEffort.setItemText(0, _translate("StartingSettings", "Maximum"))
        self.comboBoxComputationEffort.setItemText(1, _translate("StartingSettings", "Normal"))
        self.comboBoxComputationEffort.setItemText(2, _translate("StartingSettings", "Low"))
        self.label_16.setText(_translate("StartingSettings", "Crossover prob:"))
        self.label_17.setText(_translate("StartingSettings", "Mutation prob:"))
        self.comboBoxPopulationSize.setItemText(0, _translate("StartingSettings", "10"))
        self.comboBoxPopulationSize.setItemText(1, _translate("StartingSettings", "20"))
        self.comboBoxPopulationSize.setItemText(2, _translate("StartingSettings", "50"))
        self.comboBoxPopulationSize.setItemText(3, _translate("StartingSettings", "100"))
        self.comboBoxPopulationSize.setItemText(4, _translate("StartingSettings", "Adaptive"))
        self.label_18.setText(_translate("StartingSettings", "Tot duration (sec):"))
        self.buttonStart.setText(_translate("StartingSettings", "Start"))

settingsGuiWindow = None

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    settingsGuiWindow = QtWidgets.QMainWindow()
    ui = Ui_StartingSettings()
    ui.setupUi(settingsGuiWindow)
    settingsGuiWindow.show()
    sys.exit(app.exec_())